import type { Copy } from './copy';

export const copy: Copy = {
  language: 'Language',
  siteTitle: 'Babel Life',
  homeTitle: 'Babel Life — Possible Lives Inspired by Borges’ Library of Babel',
  eyebrow: 'BABEL LIFE',
  heading: 'Somewhere in the Library of Babel, every writable life already exists.',
  dek: 'With just 25 symbols, the Library contains more books than there are atoms in the observable universe. Somewhere among them are all the lives you could have lived.',
  libraryScaleLabel: 'THE LIBRARY',
  libraryScaleMantissa: '≈ 1.96 × 10',
  libraryScaleSpokenMantissa: 'approximately 1.96 times ten',
  libraryScaleExponent: '1,834,097',
  libraryScaleUnit: 'books',
  libraryScaleMeta: '25 symbols · 1,312,000 positions',
  universeScaleLabel: 'THE OBSERVABLE UNIVERSE',
  universeScaleMantissa: '≈ 10',
  universeScaleExponent: '80',
  universeScaleUnit: 'atoms',
  scalePower: '{mantissa} to the power of {exponent} {unit}',
  lede: 'Open one.',
  cardEyebrow: 'THERE IS ALREADY A BOOK IN WHICH…',
  openThisLife: 'OPEN THIS LIFE',
  somethingStranger: 'SHOW ME SOMETHING STRANGER',
  showAll: 'SHOW ALL 27',
  backToWall: 'Wall of Lives',
  found: 'YOU FOUND THE BOOK',
  alreadyHere: 'This book was already here.',
  nearbyVolumes: 'NEARBY BOOKS',
  openNearby: 'OPEN',
  shelfEyebrow: 'ONE SHELF',
  openThisShelf: 'open this shelf',
  shelfHolds: [
    'Thirty-two volumes stand here. None of them can be read.',
    'Thirty-two volumes stand here. One of them can be read.',
    'Thirty-two volumes stand here. Two of them can be read.',
    'Thirty-two volumes stand here. Three of them can be read.',
    'Thirty-two volumes stand here. Four of them can be read.',
  ],
  notLegible: 'illegible',
  volumeLabel: 'Volume',
  previousShelf: 'PREVIOUS SHELF',
  nextShelf: 'NEXT SHELF',
  previousVolume: 'PREVIOUS VOLUME',
  nextVolume: 'NEXT VOLUME',
  noLegibleVolume: 'NO LEGIBLE VOLUME',
  noLegibleNote: 'A volume stands at this address. Nothing in it can be read.',
  browseShelf: 'BROWSE THIS SHELF',
  pageOf: 'One page of four hundred and ten.',
  pageDescription: 'A page of symbols that spell nothing in any language.',
  consulted: 'Consulted at {time} on a {day}.',
  days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  anotherLife: 'SHOW ME ANOTHER LIFE',
  invalidAddress: 'This address is not in this edition.',
  invalidAddressNote: 'Every volume here has a permanent address. This is not one of them.',
  enterTheLibrary: 'Enter the Library',
  attribution: 'Inspired by Jorge Luis Borges.',
  copyright: '© 2026 Rolando Fernández. All rights reserved.',
  aboutHeading: 'About Babel Life',
  aboutBody:
    'Babel Life is an independent literary project inspired by Jorge Luis Borges’ short story “The Library of Babel”. It is not affiliated with, endorsed by or published by the Borges estate or any publisher. No passage from Borges’ story is reproduced here. Its passages and coordinates belong to this edition. This is fiction: the site cannot identify, predict or estimate anyone’s future.',
  legalHeading: 'Legal & privacy',
  legalBody:
    'Babel Life is currently a non-commercial personal project. It does not sell goods or services, offer user accounts, accept form submissions or serve advertising. It uses Cloudflare Web Analytics for aggregate traffic and performance metrics; this service does not use cookies or localStorage for usage metrics and does not collect or use visitors’ personal data. Hosting providers may process technical request data needed to deliver, secure and operate the site.',
  legalOwner: 'Maintained by Rolando Fernández in Spain.',
  wallCountPartial: '{count} of {total} books.',
  wallCountAll: 'All {total} books.',
  editionLabel: 'THIS EDITION',
  editionBooks: '{count} books',
  editionOnWall: '{count} on the wall',
  countWords: [
    'Zero', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine',
    'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen',
    'Seventeen', 'Eighteen', 'Nineteen', 'Twenty', 'Twenty-one', 'Twenty-two',
    'Twenty-three', 'Twenty-four', 'Twenty-five', 'Twenty-six', 'Twenty-seven',
  ],
  announceStranger: '{count} other lives.',
  announceAll: 'All twenty-seven lives.',
  coordHexagon: 'Hexagon',
  coordWall: 'Wall',
  coordShelf: 'Shelf',
  coordVolume: 'Volume',
  cardAddress: 'Hexagon {hexagon} · Volume {volume}',
  shelfVolumesLabel: 'Volumes on this shelf',
  locatorHeading: 'WHERE THIS BOOK STANDS',
  locatorHere: 'VOLUME {n} · YOU ARE HERE',
  locatorAlsoLegible: ' Also legible on this shelf',
  locatorSolo: ' No other legible volume on this shelf',
};
