import type { Copy } from './copy';

export const copy: Copy = {
  language: 'Idioma',
  siteTitle: 'Babel Life',
  homeTitle: 'Babel Life — Vidas posibles inspiradas en la Biblioteca de Babel de Borges',
  eyebrow: 'BABEL LIFE',
  heading: 'En algún lugar de la Biblioteca de Babel, toda vida posible ya está escrita.',
  dek: 'Con solo 25 símbolos, la Biblioteca contiene más libros que átomos hay en el universo observable. En algún lugar entre ellos están todas las vidas que podrías haber vivido.',
  libraryScaleLabel: 'LA BIBLIOTECA',
  libraryScaleMantissa: '≈ 1,96 × 10',
  libraryScaleSpokenMantissa: 'aproximadamente 1,96 por diez',
  libraryScaleExponent: '1.834.097',
  libraryScaleUnit: 'libros',
  libraryScaleMeta: '25 símbolos · 1.312.000 posiciones',
  universeScaleLabel: 'EL UNIVERSO OBSERVABLE',
  universeScaleMantissa: '≈ 10',
  universeScaleExponent: '80',
  universeScaleUnit: 'átomos',
  scalePower: '{mantissa} elevado a {exponent} {unit}',
  lede: 'Abre uno.',
  cardEyebrow: 'YA HAY UN LIBRO EN EL QUE…',
  openThisLife: 'ABRIR ESTA VIDA',
  somethingStranger: 'MOSTRARME ALGO MÁS EXTRAÑO',
  showAll: 'MOSTRAR LAS 27',
  backToWall: 'Muro de vidas',
  found: 'HAS ENCONTRADO EL LIBRO',
  alreadyHere: 'Este libro ya estaba aquí.',
  nearbyVolumes: 'LIBROS CERCANOS',
  openNearby: 'ABRIR',
  shelfEyebrow: 'UN ANAQUEL',
  openThisShelf: 'abrir este anaquel',
  shelfHolds: [
    'Aquí hay treinta y dos volúmenes. Ninguno de ellos se puede leer.',
    'Aquí hay treinta y dos volúmenes. Uno de ellos se puede leer.',
    'Aquí hay treinta y dos volúmenes. Dos de ellos se pueden leer.',
    'Aquí hay treinta y dos volúmenes. Tres de ellos se pueden leer.',
    'Aquí hay treinta y dos volúmenes. Cuatro de ellos se pueden leer.',
  ],
  notLegible: 'ilegible',
  volumeLabel: 'Volumen',
  previousShelf: 'ANAQUEL ANTERIOR',
  nextShelf: 'ANAQUEL SIGUIENTE',
  previousVolume: 'VOLUMEN ANTERIOR',
  nextVolume: 'VOLUMEN SIGUIENTE',
  noLegibleVolume: 'NINGÚN VOLUMEN LEGIBLE',
  noLegibleNote: 'En esta dirección hay un volumen. Nada de lo que contiene se puede leer.',
  browseShelf: 'RECORRER ESTE ANAQUEL',
  pageOf: 'Una página de cuatrocientas diez.',
  pageDescription: 'Una página de símbolos que no dicen nada en ninguna lengua.',
  consulted: 'Consultado a las {time} de un {day}.',
  days: ['domingo', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado'],
  anotherLife: 'MOSTRARME OTRA VIDA',
  invalidAddress: 'Esta dirección no está en esta edición.',
  invalidAddressNote: 'Cada volumen tiene aquí una dirección permanente. Esta no es una de ellas.',
  enterTheLibrary: 'Entrar en la Biblioteca',
  homage:
    'Babel Life es un humilde homenaje a «La biblioteca de Babel» (1941), de Jorge Luis Borges. Proyecto independiente: no reproduce el cuento ni está vinculado a sus herederos ni a sus editores.',
  copyright: '© 2026 Rolando Fernández. Todos los derechos reservados.',
  supportPrefix: 'Apoya esta edición',
  supportLabel: 'Invítame a un café',
  dedication: 'A Jorge Luis Borges, que imaginó la Biblioteca.',
  aboutHeading: 'Sobre Babel Life',
  aboutBody:
    'Babel Life es un proyecto literario independiente inspirado en el cuento «La biblioteca de Babel», de Jorge Luis Borges. No está afiliado, avalado ni publicado por los herederos de Borges ni por ninguna editorial. Aquí no se reproduce ningún pasaje del cuento. Los pasajes y las coordenadas pertenecen a esta edición. Esto es ficción: el sitio no puede identificar, predecir ni estimar el futuro de nadie.',
  legalHeading: 'Aviso legal y privacidad',
  legalBody:
    'Babel Life es un proyecto literario personal e independiente. No vende productos ni servicios, no ofrece cuentas de usuario, no acepta formularios ni muestra publicidad. El apoyo voluntario mediante Buy Me a Coffee es opcional y no da acceso a bienes, servicios, contenidos ni otras contraprestaciones. Utiliza Cloudflare Web Analytics para métricas agregadas de tráfico y rendimiento; este servicio no usa cookies ni localStorage para las métricas de uso y no recoge ni utiliza datos personales de los visitantes. Los proveedores de alojamiento pueden tratar los datos técnicos de las peticiones necesarios para servir, proteger y operar el sitio.',
  legalOwner: 'Mantenido por Rolando Fernández en España.',
  wallCountPartial: '{count} de {total} libros.',
  wallCountAll: 'Los {total} libros.',
  editionLabel: 'ESTA EDICIÓN',
  editionBooks: '{count} libros',
  editionOnWall: '{count} en el muro',
  countWords: [
    'Cero', 'Uno', 'Dos', 'Tres', 'Cuatro', 'Cinco', 'Seis', 'Siete', 'Ocho', 'Nueve',
    'Diez', 'Once', 'Doce', 'Trece', 'Catorce', 'Quince', 'Dieciséis', 'Diecisiete',
    'Dieciocho', 'Diecinueve', 'Veinte', 'Veintiuno', 'Veintidós', 'Veintitrés',
    'Veinticuatro', 'Veinticinco', 'Veintiséis', 'Veintisiete',
  ],
  announceStranger: '{count} vidas más.',
  announceAll: 'Las veintisiete vidas.',
  coordHexagon: 'Hexágono',
  coordWall: 'Pared',
  coordShelf: 'Anaquel',
  coordVolume: 'Volumen',
  cardAddress: 'Hexágono {hexagon} · Volumen {volume}',
  shelfVolumesLabel: 'Volúmenes de este anaquel',
  locatorHeading: 'DÓNDE ESTÁ ESTE LIBRO',
  locatorHere: 'VOLUMEN {n} · ESTÁS AQUÍ',
  locatorAlsoLegible: ' También legible en este anaquel',
  locatorSolo: ' Ningún otro volumen legible en este anaquel',
};
