/** Every visitor-facing string outside the catalog. */
export const copy = {
  eyebrow: 'THE LIBRARY OF LIVES',
  heading: 'Somewhere in the Library, every writable life already exists.',
  lede: 'Open one.',
  cardEyebrow: 'THERE IS ALREADY A BOOK IN WHICH\u2026',
  openThisLife: 'OPEN THIS LIFE',
  somethingStranger: 'SHOW ME SOMETHING STRANGER',
  showAll: 'SHOW ALL 24',
  backToWall: 'Wall of Lives',
  found: 'YOU FOUND THE BOOK',
  alreadyHere: 'This book was already here.',
  nearbyVolumes: 'NEARBY VOLUMES',
  // The shelf, and the addresses on it that hold nothing this edition can print.
  shelfEyebrow: 'ONE SHELF',
  openThisShelf: 'open this shelf',
  shelfHolds: 'Thirty-two volumes stand here. {legible} of them can be read.',
  notLegible: 'not legible',
  volumeLabel: 'Volume',
  previousShelf: 'PREVIOUS SHELF',
  nextShelf: 'NEXT SHELF',
  previousVolume: 'PREVIOUS VOLUME',
  nextVolume: 'NEXT VOLUME',
  noLegibleVolume: 'NO LEGIBLE VOLUME',
  noLegibleNote: 'A volume stands at this address. Nothing in it can be read.',
  browseShelf: 'BROWSE THIS SHELF',
  // A record of this consultation, not a claim about the reader.
  consulted: 'Consulted at {time} on a {day}.',
  anotherLife: 'SHOW ME ANOTHER LIFE',
  invalidAddress: 'This address is not in this edition.',
  invalidAddressNote: 'Every volume here has a permanent address. This is not one of them.',
  enterTheLibrary: 'Enter the Library',
  attribution: 'After Jorge Luis Borges.',
  aboutHeading: 'About this Library',
  aboutBody:
    'This is a curated reading experience inspired by Borges. Its passages are authored, and its coordinates belong to this edition. It cannot identify anyone’s future.',
} as const;
