import type { Copy } from './copy';

export const copy: Copy = {
  language: 'Idioma',
  siteTitle: 'Babel Life',
  homeTitle: 'Babel Life — Vidas posibles inspiradas en la Biblioteca de Babel de Borges',
  eyebrow: 'BABEL LIFE',
  heading: 'En algún lugar de la Biblioteca de Babel, toda vida posible ya está escrita.',
  dek: 'Con solo 25 símbolos, la Biblioteca contiene más libros que átomos hay en el universo observable. En algún lugar entre ellos están todas las vidas que podrías haber vivido.',
  libraryScaleLabel: 'LA BIBLIOTECA',
  libraryScaleMantissa: '≈ 1,96 × 10',
  libraryScaleExponent: '1.834.097',
  libraryScaleUnit: 'libros',
  libraryScaleMeta: '25 símbolos · 1.312.000 posiciones',
  universeScaleLabel: 'EL UNIVERSO OBSERVABLE',
  universeScaleMantissa: '≈ 10',
  universeScaleExponent: '80',
  universeScaleUnit: 'átomos',
  lede: 'Abre uno.',
  cardEyebrow: 'YA HAY UN LIBRO EN EL QUE…',
  openThisLife: 'ABRIR ESTA VIDA',
  somethingStranger: 'MOSTRARME ALGO MÁS EXTRAÑO',
  showAll: 'MOSTRAR LAS 25',
  backToWall: 'Pared de vidas',
  found: 'HAS ENCONTRADO EL LIBRO',
  alreadyHere: 'Este libro ya estaba aquí.',
  nearbyVolumes: 'VOLÚMENES CERCANOS',
  openNearby: 'ABRIR',
  shelfEyebrow: 'UNA ESTANTERÍA',
  openThisShelf: 'abrir esta estantería',
  shelfHolds: [
    'Aquí hay treinta y dos volúmenes. Ninguno de ellos se puede leer.',
    'Aquí hay treinta y dos volúmenes. Uno de ellos se puede leer.',
    'Aquí hay treinta y dos volúmenes. Dos de ellos se pueden leer.',
    'Aquí hay treinta y dos volúmenes. Tres de ellos se pueden leer.',
    'Aquí hay treinta y dos volúmenes. Cuatro de ellos se pueden leer.',
  ],
  notLegible: 'ilegible',
  volumeLabel: 'Volumen',
  previousShelf: 'ESTANTERÍA ANTERIOR',
  nextShelf: 'ESTANTERÍA SIGUIENTE',
  previousVolume: 'VOLUMEN ANTERIOR',
  nextVolume: 'VOLUMEN SIGUIENTE',
  noLegibleVolume: 'NINGÚN VOLUMEN LEGIBLE',
  noLegibleNote: 'En esta dirección hay un volumen. Nada de lo que contiene se puede leer.',
  browseShelf: 'RECORRER ESTA ESTANTERÍA',
  lookInside: 'MIRAR DENTRO',
  pageOf: 'Una página de cuatrocientas diez.',
  pageDescription: 'Una página de símbolos que no dicen nada en ninguna lengua.',
  consulted: 'Consultado a las {time} de un {day}.',
  days: ['domingo', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado'],
  anotherLife: 'MOSTRARME OTRA VIDA',
  invalidAddress: 'Esta dirección no está en esta edición.',
  invalidAddressNote: 'Cada volumen tiene aquí una dirección permanente. Esta no es una de ellas.',
  enterTheLibrary: 'Entrar en la Biblioteca',
  attribution: 'Inspirado en Jorge Luis Borges.',
  copyright: '© 2026 Rolando Fernández. Todos los derechos reservados.',
  aboutHeading: 'Sobre Babel Life',
  aboutBody:
    'Babel Life es un proyecto literario independiente inspirado en el cuento «La biblioteca de Babel», de Jorge Luis Borges. No está afiliado, avalado ni publicado por los herederos de Borges ni por ninguna editorial. Aquí no se reproduce ningún pasaje del cuento. Los pasajes y las coordenadas pertenecen a esta edición. Esto es ficción: el sitio no puede identificar, predecir ni estimar el futuro de nadie.',
  legalHeading: 'Aviso legal y privacidad',
  legalBody:
    'Babel Life es, por ahora, un proyecto personal no comercial. No vende productos ni servicios, no ofrece cuentas de usuario, no acepta formularios ni muestra publicidad. Utiliza Cloudflare Web Analytics para métricas agregadas de tráfico y rendimiento; este servicio no usa cookies ni localStorage para las métricas de uso y no recoge ni utiliza datos personales de los visitantes. Los proveedores de alojamiento pueden tratar los datos técnicos de las peticiones necesarios para servir, proteger y operar el sitio.',
  legalOwner: 'Mantenido por Rolando Fernández en España.',
  wallCountPartial: 'Doce de veinticinco volúmenes.',
  wallCountAll: 'Los veinticinco volúmenes.',
  announceStranger: 'Otras trece vidas.',
  announceAll: 'Las veinticinco vidas.',
  coordHexagon: 'Hexágono',
  coordWall: 'Pared',
  coordShelf: 'Estantería',
  coordVolume: 'Volumen',
  cardAddress: 'Hexágono {hexagon} · Volumen {volume}',
  shelfVolumesLabel: 'Volúmenes de esta estantería',
  locatorHeading: 'DÓNDE ESTÁ ESTE LIBRO',
  locatorHere: 'VOLUMEN {n} · ESTÁS AQUÍ',
  locatorAlsoLegible: ' También legible en esta estantería',
  locatorSolo: ' Ningún otro volumen legible en esta estantería',
  locatorAria: 'Volumen {n} de {total} en esta estantería. Ver esta estantería.',
  intervalAria:
    'Dos segundos, de 08:14:00 a 08:14:02, frente a treinta y un años. Las dos escalas están separadas.',
  intervalYears: 'treinta y un años',
};
