/** Every visitor-facing string outside the catalog. */
export const copy = {
  eyebrow: 'BABEL LIFE',
  heading: 'Somewhere in the Library of Babel, every writable life already exists.',
  dek: 'With just 25 symbols, the Library contains more books than there are atoms in the observable universe. Somewhere among them are all the lives you could have lived.',
  lede: 'Open one.',
  cardEyebrow: 'THERE IS ALREADY A BOOK IN WHICH…',
  openThisLife: 'OPEN THIS LIFE',
  somethingStranger: 'SHOW ME SOMETHING STRANGER',
  showAll: 'SHOW ALL 24',
  backToWall: 'Wall of Lives',
  found: 'YOU FOUND THE BOOK',
  alreadyHere: 'This book was already here.',
  nearbyVolumes: 'NEARBY VOLUMES',
  // The shelf, and the addresses on it that hold nothing this edition can print.
  shelfEyebrow: 'ONE SHELF',
  openThisShelf: 'open this shelf',
  shelfHolds: 'Thirty-two volumes stand here. {legible} of them can be read.',
  notLegible: 'not legible',
  volumeLabel: 'Volume',
  previousShelf: 'PREVIOUS SHELF',
  nextShelf: 'NEXT SHELF',
  previousVolume: 'PREVIOUS VOLUME',
  nextVolume: 'NEXT VOLUME',
  noLegibleVolume: 'NO LEGIBLE VOLUME',
  noLegibleNote: 'A volume stands at this address. Nothing in it can be read.',
  browseShelf: 'BROWSE THIS SHELF',
  // One page of a volume nobody can read. Not an account of anything.
  lookInside: 'LOOK INSIDE',
  pageOf: 'One page of four hundred and ten.',
  pageDescription: 'A page of symbols that spell nothing in any language.',
  // A record of this consultation, not a claim about the reader.
  consulted: 'Consulted at {time} on a {day}.',
  anotherLife: 'SHOW ME ANOTHER LIFE',
  invalidAddress: 'This address is not in this edition.',
  invalidAddressNote: 'Every volume here has a permanent address. This is not one of them.',
  enterTheLibrary: 'Enter the Library',
  attribution: 'Inspired by Jorge Luis Borges.',
  copyright: '© 2026 Rolando Fernández. All rights reserved.',
  aboutHeading: 'About Babel Life',
  aboutBody:
    'Babel Life is an independent literary project inspired by Jorge Luis Borges’ short story “The Library of Babel”. It is not affiliated with, endorsed by or published by the Borges estate or any publisher. No passage from Borges’ story is reproduced here. Its passages and coordinates belong to this edition. This is fiction: the site cannot identify, predict or estimate anyone’s future.',
  legalHeading: 'Legal & privacy',
  legalBody:
    'Babel Life is currently a non-commercial personal project. It does not sell goods or services, offer user accounts, accept form submissions, serve advertising or intentionally profile visitors. The site itself does not set advertising or analytics cookies. Hosting providers may process technical request data needed to deliver, secure and operate the site.',
  legalOwner: 'Maintained by Rolando Fernández in Spain.',
} as const;
